<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NutriTrack.UI</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NutriTrack.Core\NutriTrack.Core.csproj" />
    <ProjectReference Include="..\NutriTrack.Data\NutriTrack.Data.csproj" />
  </ItemGroup>

</Project>
