#pragma checksum "..\..\..\..\Views\RecipesView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1764C976C4755242C5584A217851BAEEFDDB9FD4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NutriTrack.UI.Converters;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace NutriTrack.UI.Views {
    
    
    /// <summary>
    /// RecipesView
    /// </summary>
    public partial class RecipesView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 85 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition DetailColumn;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SearchBox;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CuisineCombo;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox TimeCombo;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SortCombo;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel CategoryChips;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ResultCountText;
        
        #line default
        #line hidden
        
        
        #line 165 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl RecipeItemsControl;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel EmptyState;
        
        #line default
        #line hidden
        
        
        #line 182 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DetailBorder;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel DetailPanel;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DetailTitle;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DetailMeta;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DetailSensitivities;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl DetailIngredients;
        
        #line default
        #line hidden
        
        
        #line 210 "..\..\..\..\Views\RecipesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl DetailInstructions;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/NutriTrack.UI;component/views/recipesview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\RecipesView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 2:
            this.DetailColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 3:
            this.SearchBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 114 "..\..\..\..\Views\RecipesView.xaml"
            this.SearchBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 4:
            this.CuisineCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 131 "..\..\..\..\Views\RecipesView.xaml"
            this.CuisineCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 5:
            this.TimeCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 134 "..\..\..\..\Views\RecipesView.xaml"
            this.TimeCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 6:
            this.SortCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 143 "..\..\..\..\Views\RecipesView.xaml"
            this.SortCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 150 "..\..\..\..\Views\RecipesView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearFilters_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.CategoryChips = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 9:
            this.ResultCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.RecipeItemsControl = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 11:
            this.EmptyState = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 12:
            this.DetailBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 13:
            this.DetailPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 14:
            this.DetailTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            
            #line 192 "..\..\..\..\Views\RecipesView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseDetail_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.DetailMeta = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.DetailSensitivities = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.DetailIngredients = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 19:
            this.DetailInstructions = ((System.Windows.Controls.ItemsControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 18 "..\..\..\..\Views\RecipesView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RecipeCard_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

